# Generated by Django 5.2.6 on 2025-09-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='Аноним', max_length=100, verbose_name='Имя автора'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='Аноним', max_length=100, verbose_name='Имя автора'),
        ),
    ]
